<?php

declare(strict_types=1);

/**
 * @file
 * Provides a daily quote entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function daily_quote_theme(): array {
  return [
    'daily_quote' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for daily quote templates.
 *
 * Default template: daily-quote.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the daily quote information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_daily_quote(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function daily_quote_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish daily quotes.
      $storage = \Drupal::entityTypeManager()->getStorage('daily_quote');
      $daily_quote_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($daily_quote_ids) as $daily_quote) {
        $daily_quote->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize daily quotes.
      $storage = \Drupal::entityTypeManager()->getStorage('daily_quote');
      $daily_quote_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($daily_quote_ids) as $daily_quote) {
        $daily_quote->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function daily_quote_user_predelete(UserInterface $account): void {
  // Delete daily quotes that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('daily_quote');
  $daily_quote_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($daily_quote_ids)
  );
}
