<?php

/**
 * @file
 */

use Drupal\user\UserInterface;
use Drupal\node\NodeInterface;

/**
 *activity_logger_user_login
 */
function activity_logger_user_login(UserInterface $account) {
  actitvity_logger_log_activity($account->id(), 'user logged in');
}

/**
 *activity_logger_user_logout
 */
function activity_logger_user_logout(UserInterface $account) {
  actitvity_logger_log_activity($account->id(), 'user logger out');
}

/**
 *activity_logger_node_insert
 */
function activity_logger_node_insert(NodeInterface $node) {
  $current_user = \Drupal::currentUser();
  if ($current_user->isAuthenticated()) {
    actitvity_logger_log_activity($current_user->id(), 'Created node: ' . $node->getTitle());
  }
}

/**
 *activity_logger_node_delete
 */
function activity_logger_node_delete(NodeInterface $node) {
  $currentUser = \Drupal::currentUser();
  if ($currentUser->isAuthenticated()) {
    actitvity_logger_log_activity($currentUser->id(), 'node deleted' . $node->getTitle());
  }
}

/**
 *activity_logger_node_update
 */
function activity_logger_node_update(NodeInterface $node) {
  $currentUser = \Drupal::currentUser();
  if ($currentUser->isAuthenticated()) {
    actitvity_logger_log_activity($currentUser->id(), 'node updated' . $node->getTitle());
  }
}

/**
 *actitvity_logger_log_activity
 */
function actitvity_logger_log_activity($uid, $activity) {
  $connection = \Drupal::database();
  $connection->insert('user_activities')
    ->fields([
      'uid' => $uid,
      'activity' => $activity,
      'timestamp' => \Drupal::time()->getCurrentTime(),
    ])
    ->execute();
}
